-- AlterTable
ALTER TABLE "Letter" ADD COLUMN IF NOT EXISTS "draftContent" TEXT;
ALTER TABLE "Letter" ADD COLUMN IF NOT EXISTS "draftPdfR2Key" TEXT;
ALTER TABLE "Letter" ADD COLUMN IF NOT EXISTS "signedPdfR2Key" TEXT;
ALTER TABLE "Letter" ADD COLUMN IF NOT EXISTS "attorneyVerified" BOOLEAN NOT NULL DEFAULT false;
